### ISSUE TITLE
Allow multiple LDAP servers

### ISSUE THREAD

**Issue by l-ohlen-ericsson** [eiffel-community/eiffel-intelligence#192]
### Description
Support multiple LDAP servers

### Motivation
With the current support for a single LDAP server there is a risk of outage of  EI if that single server has some outage.

### Exemplification
LDAP server outage

### Benefits
Better availabllity of EI

### Possible Drawbacks
A bit more complicated authentication logic

**Comment by Christoffer-Cortes** [comment]
https://github.com/eiffel-community/eiffel-intelligence/pull/315

**Comment by Christoffer-Cortes** [comment]
This issue has been resolved.
