### ISSUE TITLE
Images not available in documentation.

### ISSUE THREAD

**Issue by evasiba-ericsson** [eiffel-community/eiffel-intelligence#241]
Images not available in documentation.

### Description
Images missing from documentation, example: 
https://eiffel-community.github.io/eiffel-intelligence/existing-rules-files.html

Images in "wiki/images/" are supposed to be copied to "wiki/resources/images/" during mvn site phase. However the .png files are not pushed to gh-pages branch, and thus not visible in site documentation...

### Motivation
Users need the images to understand this part of the documentation

### Exemplification
None

**Comment by e-pettersson-ericsson** [comment]
I'm not sure this issue is applicable anymore, since [this PR](https://github.com/eiffel-community/eiffel-intelligence/pull/243) seemed to fix the issue of not copying resources. Executing the sopy-resources plugin during pre-site phase ensures the images are available for mvn site plugin to use.
