### ISSUE TITLE
Move IntegrationsTests docker-compose yaml file

### ISSUE THREAD

**Issue by tobiasake** [eiffel-community/eiffel-intelligence#248]
### Description
Integration tests docker-compose.yml and docker-env.bash should be moved to the integration test resources or docker folder:
- src/integrationtest/resources
or
- src/integrationtest/docker

These test related files should not be located in the root directory of the repository. 

Remember to update the .travis file and docker-compose command line:
docker-compose -f path/to/docker-compose.yml up -d

**Comment by e-pettersson-ericsson** [comment]
This issue is fixed with the PR #265
