### ISSUE TITLE
Save response from failed notification in database

### ISSUE THREAD

**Issue by vasile-baluta** [eiffel-community/eiffel-intelligence#254]
### Description
Today Eiffel Intelligence back-end does not store any information about a failed notification in the database. It is logged to the console, but users who does not have access to this does not see why a notification failed. 

When a subscription triggers EI attempts to notify about this using REST POST or MAIL. If either of those fails for some reason, EI currently saves 1) subscription name, 2) time 3) state of the aggregated object when subscription triggered 4) notification meta. This is not enough information for the user if they want to find out WHY something went wrong.

We also need to document these changes, what happens when a subscription fails. 

### Motivation
No information about what happens when a subscription fails. The user still has to search logs when they notice a notification has not happened.

There is an issue https://github.com/eiffel-community/eiffel-intelligence-frontend/issues/256 in front-end about making any failed notification visible in the GUI for users to readily be able to debug their flows. However, in order to be able to visualize the WHY in the GUI back-end needs to store this information also.

### Benefits
Easier to use Eiffel Intelligence and to ensure your subscriptions are working properly. If something goes wrong, the user can understand why this happened (e.g. could be a misspelled URL or MAIL, or REST service down) and attempt to fix this.

**Comment by e-pettersson-ericsson** [comment]
We have a section explaining the use of missed notifications described here: https://github.com/eiffel-community/eiffel-intelligence/blob/master/wiki/markdown/step-by-step-subscription-notification.md#missed-notifications but I assume this is not what you mean? Can you please elaborate this issue a bit?
