### ISSUE TITLE
Show which rules are being used in Eiffel Intelligence

### ISSUE THREAD

**Issue by e-pettersson-ericsson** [eiffel-community/eiffel-intelligence#259]
### Description
It would be nice to have a separate API endpoint for showing which rules are being used in the selected backend instance. Performing a GET request towards /rules and it would fetch the rules in a json format.

This would require implementation both in EI backend and EI frontend (both to fetch the rules in json format and to display them in the frontend).

### Motivation
It would be easier to identify which rules are being used in the EI backend instance. If the rules can be viewed in the GUI (and via curl command) it becomes easier for the user to understand how to write subscriptions.

### Exemplification
Let's say the rules has been updated for EI backend sourcechange. Then you want to know how the new rules look like, and not just get the name of the file. As a user, you can look in the EI frontend GUI under Eiffel Intelligence info, or use curl command and get the rules being used in a json format.

The REST API would need to be updated according to below example:

GET /rules      <--- Retrieves which rules are being used

### Benefits
Easier to write subscriptions for EI when the rules can be viewed and compared against, when writing JMESPATH expressions in the subscription. 

### Possible Drawbacks
None that I can think of.

**Comment by Christoffer-Cortes** [comment]
This issue has been handled in: https://github.com/eiffel-community/eiffel-intelligence/pull/300
