### ISSUE TITLE
Restructure of endpoints

### ISSUE THREAD

**Issue by e-pettersson-ericsson** [eiffel-community/eiffel-intelligence#291]
### Description
The REST API entrypoints need to be improved in various ways.
e.g.
- /queryAggregatedObject?ID={id} directly fetches a resource of the type aggregatedObject and the endpoint should be structured in the same way resources are fetched in the /subscription endpoint.
- /rules/rule-check endpoint does not having anything directly to do with the root /rules resource which is now used to get the active rules in the back-end. The should be broken out to separate endpoint.
- There are different naming conventions being used for the entrypoints: in some cases (most often) camelCase is used, but in some places spinal-case (dashes between words) is used. We should be consistent and use only one naming convention. Personally I prefer the spinal-case, but this means changing many entrypoints. It looks more clean, and it is easier to read in a URL.

There are more improvements that can be done and an investigation and proposal for the changes needs to be made.

**NOTE**: If this is to be implemented, this must also be changed in the Eiffel Intelligence frontend.

Related issues can be found here:
https://github.com/eiffel-community/eiffel-intelligence/issues/343
https://github.com/eiffel-community/eiffel-intelligence/issues/344
https://github.com/eiffel-community/eiffel-intelligence/issues/345
https://github.com/eiffel-community/eiffel-intelligence/issues/346
https://github.com/eiffel-community/eiffel-intelligence/issues/347
https://github.com/eiffel-community/eiffel-intelligence/issues/348
https://github.com/eiffel-community/eiffel-intelligence/issues/339
https://github.com/eiffel-community/eiffel-intelligence/issues/340

### Motivation
We want all endpoints to follow the same pattern e.g. getting single/multi/sub resources, naming and grouping etc.

### Exemplification
Here is a table of all the proposed endpoint changes.

Method | Old | New
-- | -- | --
GET | /subscriptions | /subscriptions
POST | /subscriptions | /subscriptions
PUT | /subscriptions | /subscriptions
DELETE | /subscriptions/{subscriptionName} | /subscriptions/{subscriptionName}
DELETE | - | /subscriptions?subscriptionNames=Sub1,Sub2,Sub3
GET | /subscriptions/{subscriptionName} | /subscriptions/{subscriptionName}
GET | - | /subscriptions?subscriptionNames=Sub1,Sub2,Sub3
GET | - | /subscriptions/{subscriptionName}/failed-notifications
  |   |  
GET | /rules | /rules
  |   |  
POST | /rules/rule-check | /rule-test/run-single-rule
POST | /rules/rule-check/aggregation | /rule-test/run-full-aggregation
GET | /rules/rule-check/testRulePageEnabled | /rule-test/enabled
  |   |  
GET | /queryAggregatedObject?ID={id} | /aggregated-objects/{id}
POST | /query | /aggregated-objects/query
GET | /queryMissedNotifications?subscriptionName=Sub1 | /failed-notifications?subscriptionNames=Sub1,Sub2,Sub3
  |   |  
GET | /auth | /authentication/enabled
GET | /auth/login | /authentication/login
GET | /auth/logout | /authentication/logout
  |   |  
GET | /auth/checkStatus | /status
  |   |  
GET | /download | /templates
GET | /download/subscriptionsTemplate | /templates/subscriptions
GET | /download/rulesTemplate | /templates/rules
GET | /download/eventsTemplate | /templates/events
  |   |  
GET | /information | /information
  |   |  
GET | /backend | /backends
PUT | /backend | -
DELETE | /backend | -
POST | /backend | -

### Benefits
A better structure creates a more readable and consistent REST API for Eiffel Intelligence and will lead to better maintainability.
It will be easier to understand if every endpoint both looks and behaves the same way. With improved naming and grouping it will also be easier to potentially expand the endpoint functionality in a way that makes sense.

### Possible Drawbacks
This change requires some work, and also means the Eiffel Intelligence frontend needs to be updated.
The changes would also not be backwards compatible.

**Comment by e-pettersson-ericsson** [comment]
I noticed that the PR for this #298 was not merged into master, just closed. Reopening this issue so we can discuss if we should proceed with this or not.

**Comment by e-edling-ericsson** [comment]
We had a face-to-face meeting where we discussed this issue. We concluded that all entry points will use kebab-case as well as a restructure of the entire REST-API to be more aligned with the RESTful convention(Manipulating resources).

**Comment by a-breid-ericsson** [comment]
The endpoint /backends has nothing to do with EI back-end :)

**Comment by e-pettersson-ericsson** [comment]
> The endpoint /backends has nothing to do with EI back-end :)

True, but I think this issue regards changes both in back-end and front-end and the resulting discussion includes changing the entire REST API.

**Comment by Christoffer-Cortes** [comment]
I move /backend endpoint to front-end issue, should I move it back? =S

**Comment by e-pettersson-ericsson** [comment]
I think it can still be here in this original issue, so as to get an overview of the entire REST API - but then put specific endpoints which only exist in frontend there :)

**Comment by tobiasake** [comment]
I think "/backends" can be more specific e.g. : "backend-instances" or "registered-backend-instances".

**Comment by tobiasake** [comment]
Is this the final version of all rest entrypoints list? has everyone agreed to the new names and this non-backward compatible change?

**Comment by Christoffer-Cortes** [comment]
I've closed the story for investigation after we had two meetings on this and I thought that was enough. If you want to reopen the discussion we can talk about it again.

**Comment by e-pettersson-ericsson** [comment]
I will close this issue since all of the endpoints have now been refactored both in EI back-end and EI front-end regarding the REST API changes.
