### ISSUE TITLE
Notifications done by EI when subscription triggers should be done by commons HttpRequest

### ISSUE THREAD

**Issue by a-breid-ericsson** [eiffel-community/eiffel-intelligence#306]
### Description
Currently EI uses Spring java rest template. We use commons HttpRequest for many tests, since we have this HttpRequest/Executor we should strive to use the same everywhere. 

### Motivation
Since we need to execute HttpRequests without Spring we should use the one in commons.

### Benefits
One HttpRequest/Executor

### Possible Drawbacks
HttpRequest/Executor must not be changed in a way that it breaks any functionality.

**Comment by e-pettersson-ericsson** [comment]
Is this a duplicate of issue #305 ?

**Comment by e-edling-ericsson** [comment]
I suppose @a-breid-ericsson wanted to divide the stories in two. This seems targeted for the subscription trigger only. #305 Is about switching it out for the tests.

**Comment by henning-roos** [comment]
Updated #305 to include this issue.
