### ISSUE TITLE
Clarify repeat flag for subscriptions with several requirements.

### ISSUE THREAD

**Issue by e-pettersson-ericsson** [eiffel-community/eiffel-intelligence#311]
### Description 
Wee need to update the Eiffel Intelligence documentation regarding the bahvior of repeating an already triggered subscription. What happens with subscriptions that has several requirement groups? Or one requirement but with several conditions? We need proper examples of each use case.

### Motivation
The current documentation about requirements and conditions does not describe how the repeat flag impacts the behavior.
See [front-end documentation here](https://github.com/eiffel-community/eiffel-intelligence-frontend/blob/master/wiki/markdown/add-subscription.md) and [back-end documentation here](https://github.com/eiffel-community/eiffel-intelligence/blob/master/wiki/markdown/subscriptions.md#writing-requirements-and-conditions). 

### Exemplification
What happens when a subscription has several requirements and the repeat flag is set to false? And if the repeat flag is set to true with a subscription containing several requirements?

### Benefits
Easier for users to determine whether they should have repeat set to true or false to achieve what they want.

### Possible Drawbacks
None.

**Comment by e-edling-ericsson** [comment]
By looking through the code, the behaviour should be just like it's described in the documentation. "It is possible to enable repeat, e.g. whether same subscription should be re-triggered for new additions to the aggregated object. If disabled, the notification will be triggered only the first time when conditions are fulfilled.". The notification will only be triggered once no matter what for that aggregated object. It doesn't matter if you have multiple requirements or not.
