### ISSUE TITLE
The /status endpoint should return more information

### ISSUE THREAD

**Issue by Christoffer-Cortes** [eiffel-community/eiffel-intelligence#339]
### Description
This issue is part of #291.
The idea is that it should return if the back-ends connected components are responding as well as serve as an arbitrary ping endpoint.

**NOTE:** Front-end needs changes as well. There is only one front-end issue here https://github.com/eiffel-community/eiffel-intelligence-frontend/issues/252, that you can assign yourself to if you've taken part in a restructure issue.

### Motivation
This can give slightly better feedback on the overall status of the back-end.

### Exemplification
The endpoint could return something like this:
`{"rabbitmq":true, "eiffel-er":true, "mongodb": false}`

### Benefits
In some cases in the front-end the user is unaware of certain problems with the back-end. No aggregations occur because back-end is having trouble with the message bus or mongodb goes down and it takes a 1m response timeout to find out etc.

**Comment by e-pettersson-ericsson** [comment]
These changes will be released in Eiffel Intelligence 3.0 since they are non backward compatible.
