### ISSUE TITLE
/queryMissedNotifications endpoint move to /failed-notifications 

### ISSUE THREAD

**Issue by Christoffer-Cortes** [eiffel-community/eiffel-intelligence#346]
### Description
This issue is part of #291.
At the moment missed notifications is 'sort of' part of the query group of endpoints but they have no relation. This change simplifies the naming and makes it clearer that they are two separate collections.

**NOTE:** Front-end needs changes as well. There is only one front-end issue here https://github.com/eiffel-community/eiffel-intelligence-frontend/issues/252, that you can assign yourself to if you've taken part in a restructure issue.

### Motivation
Part of the endpoint restructure.

### Exemplification
This endpoint will now become the simpler and more telling /failed-notifications.

Method | Old | New
-- | -- | --
GET | /queryMissedNotifications?subscriptionName=Sub1 | /failed-notifications?subscriptionNames=Sub1,Sub2,Sub3

### Benefits
This makes all endpoints look and behave the same way.

**Comment by e-pettersson-ericsson** [comment]
I noticed that we've gotten confused in the current behavior of the /queryMissedNotifications endpoint. Current behavior supports only a GET request with one subscriptionName only. In our suggestion of restructuring however, we've assumed the endpoint to support a GET request with a list of subscriptionNames (just like in /subscriptions endpoint) and this needs to be discussed.

Do we want to add the possibility of performing a GET request with several subscriptionNames?

Personally I like to add this possibility as it would align with several other endpoints in our REST API. + I also assume users would want the possibility to get failed notifications for several of their subscriptions at once.

**Comment by e-pettersson-ericsson** [comment]
Logic was not changed in #352 to support multiple subscriptions in the search, so this issue is still open.

**Comment by Christoffer-Cortes** [comment]
This is now closed as the endpoint now supports multiple subscriptions in the parameter.
