### ISSUE TITLE
/auth endpoint move to /authentication 

### ISSUE THREAD

**Issue by Christoffer-Cortes** [eiffel-community/eiffel-intelligence#347]
### Description
This issue is part of #291.
The auth endpoint will function as earlier but with some changes to the naming.

**NOTE:** Front-end needs changes as well. There is only one front-end issue here https://github.com/eiffel-community/eiffel-intelligence-frontend/issues/252, that you can assign yourself to if you've taken part in a restructure issue.

### Motivation
Part of the endpoint restructure.

### Exemplification
This endpoint will now be spelled out as /authentication and like in issue https://github.com/eiffel-community/eiffel-intelligence/issues/344, to check if authentication is enabled you append this semantically to the URL path.

Method | Old | New
-- | -- | --
GET | /auth | /authentication/enabled
GET | /auth/login | /authentication/login
GET | /auth/checkStatus

The previous functionality in the API endpoint /auth/checkStatus will be moved into a separate endpoint /status. See related issue #339 

### Benefits
This makes all endpoints look and behave the same way.

**Comment by e-pettersson-ericsson** [comment]
@a-breid-ericsson is it ok to close this issue now? I see that code has been updated inboth EI back-end and EI front-end.
