### ISSUE TITLE
Download endpoint changes

### ISSUE THREAD

**Issue by Christoffer-Cortes** [eiffel-community/eiffel-intelligence#348]
### Description
This issue is part of #291.
The download endpoint uses a verb as the root which is against RESTful conventions. The resources will now be grouped under the /templates endpoint.

**NOTE:** Front-end needs changes as well. There is only one front-end issue here https://github.com/eiffel-community/eiffel-intelligence-frontend/issues/252, that you can assign yourself to if you've taken part in a restructure issue.

### Motivation
Part of the endpoint restructure.

### Exemplification
These resources are now grouped under /templates and because of this the resources no longer need to append this to their names.

Method | Old | New
-- | -- | --
GET | /download | /templates
GET | /download/subscriptionsTemplate | /templates/subscriptions
GET | /download/rulesTemplate | /templates/rules
GET | /download/eventsTemplate | /templates/events

### Benefits
This makes all endpoints look and behave the same way.

**Comment by e-pettersson-ericsson** [comment]
I'll start to take a look at this endpoint changes.

**Comment by e-pettersson-ericsson** [comment]
Since the code changes have been merged I'm closing this issue. The changes will be released in Eiffel Intelligence 3.0 since they are non backward compatible.
