### ISSUE TITLE
Failed notifications GET request should not remove the notification

### ISSUE THREAD

**Issue by Christoffer-Cortes** [eiffel-community/eiffel-intelligence#354]
### Description
At the moment when you do a GET request to the failed/missed notifications endpoint the notifications is also removed after its been retrieved. It's not fully clear why this was the case. Our idea for this endpoint was for the notifications be retrieved and remain in the database for the duration of the TTL. It could of course be possible to clear notifications from the database at the request of the user by adding a DELETE operation on those resources.

### Motivation
It goes against our idea of the GUI implementation of failed notifications.

### Benefits
The user would be able to view messages several times and not have the disappear.

**Comment by e-pettersson-ericsson** [comment]
This issue still exists, as the code has not been changed and we still delete any failed notifications from the database when we retrieve them.

**Comment by henning-roos** [comment]
Is this still valid?
@Christoffer-Cortes

**Comment by Christoffer-Cortes** [comment]
No this was actually solved here https://github.com/eiffel-community/eiffel-intelligence/pull/385
