### ISSUE TITLE
Nullpointer error when mongoDB connection goes down

### ISSUE THREAD

**Issue by erik-edling** [eiffel-community/eiffel-intelligence#387]
### Description

When EI looses connection with mongoDB we will get nullpointer exceptions in several places in the code. 

One such place is line 221 in MongoDBHandler. collection will get a null value which in turn will cause the nullpointer in line 224.

Error handling should be looked through here. Maybe with exceptions instead of returning null so that we don't need to make if statements everywhere as error handling.

**Comment by henning-roos** [comment]
Related to #321
