### ISSUE TITLE
Update subscription schema in REST API description

### ISSUE THREAD

**Issue by e-pettersson-ericsson** [eiffel-community/eiffel-intelligence#394]
### Description
I noticed the RAML defined schemas for a subscription JSON object is missing authentication details. The schema should be updated to properly reflect the subscription structure. 

### Motivation
More helpful Swagger interface describing the different REST API endpoints to Eiffel Intelligence.

### Exemplification
Currently we have example JSON structures which helps the user make HTTP POST requests, like seen in the below image:
![image](https://user-images.githubusercontent.com/38855976/69523358-039d2d00-0f64-11ea-8d10-2dd3dd19f026.png)

* The authentication is missing from the JSON structure.
* The schemas are defined here: https://github.com/eiffel-community/eiffel-intelligence/tree/master/src/main/resources/public/raml/schemas 
* I would also want the JSON structure to be more specific about which fields are required and which are optional, I hope this is possible to describe in the schema.

### Benefits
Improved API description. When using the swagger interface to play around with the REST API it is very helpful if the example JSON structures are there.

### Possible Drawbacks
None that I can think of.

**Comment by Christoffer-Cortes** [comment]
authenticationType, userName and password is part of the current subscription schema.
