### ISSUE TITLE
EventHandler thread name grows in size in the log

### ISSUE THREAD

**Issue by Christoffer-Cortes** [eiffel-community/eiffel-intelligence#455]
### Description
EventHandler attaches port name to the thread name. However, the name seems to grow in size as the thread name is not forgotten and port gets reattached. This happens in instances of EI that have been operating for an extended duration where threads seem to get reused.

This regex can be used to trim, EventHandler-[0-9]+

### Motivation
Less clogged up in the logg.

### Exemplification
[EventHandler-61-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null-null]

**Comment by e-pettersson-ericsson** [comment]
The class EventHandler contains the method onMessage, where this bug needs to be fixed.

```
    @Async
    public void onMessage(Message message, Channel channel) throws Exception {
        String messageBody = new String(message.getBody());
        ObjectMapper objectMapper = new ObjectMapper();
        JsonNode node = objectMapper.readTree(messageBody);
        String id = node.get("meta").get("id").toString();
        String port = environment.getProperty("local.server.port");
        Thread.currentThread().setName(Thread.currentThread().getName() + "-" + port);
        LOGGER.debug("Thread id {} spawned for EventHandler on port: {}", Thread.currentThread().getId(), port);
        LOGGER.debug("Event {} received on port {}", id, port);
```
