### ISSUE TITLE
Migrate from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel-intelligence#525]
### Description
This repository currently has a .travis.yml file that triggers Travis CI builds for e.g. pull requests. On Dec 16, 2021, the Eiffel Technical Committee decided that existing uses of Travis CI should be migrated to GitHub Actions (see [minutes](https://hackmd.io/@eiffel-community/r1_qm09zw)).

### Motivation
Nowadays Travis CI isn't as free to use as it used to be. There's a limited number of credits given to each organization, and right now we're fairly close to the limit. In recent years GitHub Actions has been introduced and it should be adequate for most use cases.

### Benefits
Decreased risk of service interruptions if we reach the usage limit (and nobody will have to spend time on requesting increases in the limit).

### Possible Drawbacks
Probably none, unless your current .travis.yml contains steps that are very difficult to replicate in a GitHub Actions workflow.

**Comment by jainadc9** [comment]
Pushed changes for review
https://github.com/eiffel-community/eiffel-intelligence/pull/535

**Comment by magnusbaeck** [comment]
@jainadc9 Close this issue since #535 was merged?

**Comment by jainadc9** [comment]
> @jainadc9 Close this issue since #535 was merged?

Report Coverage job is still failing working on that .
